server:
  port: 20200

# swagger config
springdoc:
  swagger-ui:
    path: /api/swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: "none"
  api-docs:
    path: /api/docs
